### ISSUE TITLE
3.8 issues/not working

### ISSUE THREAD

**Issue by l300lvl** [l300lvl/analog-clock-gnome-shell-extension#1]
currently under 3.8, tested with both latest versions i've submitted to e.g.o, this fails utterly. the only reliable information provided from console is:

(gnome-shell:23157): St-ERROR **: st_widget_get_theme_node called on the widget [0x3285730 ShellGenericContainer.panel-button:first-child ("Tue 13:09")] which is not in the stage.
Trace/breakpoint trap

im opening this myself for future reference.

**Comment by l300lvl** [comment]
i have narrowed this down to have something to do with the reparent method but this will be a problem for the position preference, so for the 3.8 version i plan to submit it will only replace the clock and remain in the center, as time allows i will do more debugging

**Comment by oluc** [comment]
your version 7, uploaded at extensions.gnome.org works for me with GNOME 3.8
